const CONSTANTS = {
  BACKEND_URL: "http://43.205.89.79",
  BASIC_API_URL: "/api/v1",
  MEMBERS_API: "/admin/users",
  PRODUCTS_API: "/products",
};

CONSTANTS.BASE_URL = CONSTANTS.BACKEND_URL + CONSTANTS.BASIC_API_URL;

export default CONSTANTS;
